### ISSUE TITLE
Session at Collab Summit Vancouver 2018

### ISSUE THREAD

**Issue by mcollina** [nodejs/promises-debugging#15]
The promises session has been highly successful at Collab Summit Berlin 2018.

@benjamingr are you up to run one in Vancouver as well?

**Comment by benjamingr** [comment]
@mcollina I'd love to run one, but I'm not sure I'll be able to attend the Vancouver summit. It's really right (I'm traveling Sep 6th to Sep 28th)

I do have some exciting news regarding certain parties who have expressed interest in making significant contributions to the topic. I planned to set up another team meeting and start promoting this again once I'm back from holiday. Namely a bunch of thing are on my plate (like the survey).

If you (or @bmeurer @MayaLekova @BridgeAR ) are up for running it - I'm up for doing all the preparatory work though.

**Comment by mcollina** [comment]
I haven't followed much in the work of the team. Is there somebody that is up to run the meeting?

@BridgeAR maybe? @bmeurer @MayaLekova are any of you coming?

**Comment by BridgeAR** [comment]
I am fine to run it. @benjamingr let's sync up so we'll have a nice agenda. It would be good to progress further with a couple of things.

@bmeurer @MayaLekova if either of you would like to do that as well, we could just build a small team to organize and discuss some points beforehand.

**Comment by MayaLekova** [comment]
I won't be attending the summit myself, but would be more than happy to join a team meeting beforehand, even though there are not many news really from my side related to the topic.

**Comment by misterdjules** [comment]
It looks like this should be discussed among the whole group of people who have been active as part of this team, not just between individuals behind closed doors.

Should we instead work on this collaboratively? I would suggest creating a Google doc that everyone can edit/comment/suggest changes to as a starting point.

**Comment by BridgeAR** [comment]
We had such a session at the summit. Closing as outdated.
